force-app/main/default/objects/Cat__c/Cat__c.object-meta.xml
<CustomObject>
    <label>Cat</label>
    <nameField>
        <label>Cat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cat__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kitten</fullName>
            </value>
            <value>
                <fullName>Young Cat</fullName>
            </value>
            <value>
                <fullName>Adult Cat</fullName>
            </value>
            <value>
                <fullName>Senior Cat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cat__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cat__c/fields/Sterilized__c.field-meta.xml
<CustomField>
    <fullName>Sterilized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sterilized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cat__c/fields/Vaccinated__c.field-meta.xml
<CustomField>
    <fullName>Vaccinated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vaccinated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CatWrapper.cls
public with sharing class CatWrapper {
    @AuraEnabled
    public String id {get;set;}

    @AuraEnabled
    public String name {get;set;}

    @AuraEnabled
    public String gender {get;set;}

    @AuraEnabled
    public String age {get;set;}

    @AuraEnabled
    public Boolean sterilized {get;set;}

    @AuraEnabled
    public Boolean vaccinated {get;set;}

    public CatWrapper() {

    }

    public CatWrapper(Cat__c cat){
        this.id = cat.Id;
        this.name = cat.Name;
        this.gender = cat.Gender__c;
        this.age = cat.Age__c;
        this.sterilized = cat.Sterilized__c;
        this.vaccinated = cat.Vaccinated__c;
    }

    public static Cat__c getSobject(CatWrapper wrapper, Boolean isCreate){
        Cat__c cat = new Cat__c();
        cat.Name = wrapper.name;
        cat.Gender__c = wrapper.gender;
        cat.Age__c = wrapper.age;
        cat.Sterilized__c = wrapper.sterilized;
        cat.Vaccinated__c = wrapper.vaccinated;

        if(!isCreate){
            cat.Id = wrapper.id;
        }
        return cat;
    }
    
}