force-app/main/default/objects/Cat__c/Cat__c.object-meta.xml
<CustomObject>
    <label>Cat</label>
    <nameField>
        <label>Cat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cat__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kitten</fullName>
            </value>
            <value>
                <fullName>Young Cat</fullName>
            </value>
            <value>
                <fullName>Adult Cat</fullName>
            </value>
            <value>
                <fullName>Senior Cat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cat__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cat__c/fields/Sterilized__c.field-meta.xml
<CustomField>
    <fullName>Sterilized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sterilized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cat__c/fields/Vaccinated__c.field-meta.xml
<CustomField>
    <fullName>Vaccinated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vaccinated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CatController.cls
public with sharing class CatController {

    @AuraEnabled
    public static Map<String, CatWrapper> getAllCats(){
        Map<String, CatWrapper> mapCatsById = new Map<String, CatWrapper>();
        try {
            List<Cat__c> catList = [SELECT Id, Name, Gender__c, Age__c, Sterilized__c, Vaccinated__c FROM Cat__c];
            if(catList.size() > 0){
                for(Cat__c cat : catList){
                    mapCatsById.put(cat.Id, new CatWrapper(cat));
                }
            }
            return mapCatsById;
        } catch (Exception e) {
            return mapCatsById;
        }
    }

    @AuraEnabled
    public static CatWrapper registerCat(String name, String gender, String age, Boolean sterilized, Boolean vaccinated){
        try {
            CatWrapper wrapper = new CatWrapper();
            wrapper.name = name;
            wrapper.gender = gender;
            wrapper.age = age;
            wrapper.sterilized = sterilized;
            wrapper.vaccinated = vaccinated;

            Cat__c cat  = CatWrapper.getSobject(wrapper, true);
            insert cat;

            wrapper.id = cat.Id;
            return wrapper;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled
    public static CatWrapper updateCat(String strCat){
        try {
            CatWrapper wrapper =  (CatWrapper)JSON.deserialize(strCat, CatWrapper.class);
            Cat__c cat  = CatWrapper.getSobject(wrapper, true);
            update cat;
            return wrapper;
        } catch (Exception e) {
            return null;
        }
    }

}